const fs=require('fs');
const vm=require('vm');
const zlib=require('zlib');
const cp=require('child_process');
for(const f of ['boq/data.js','boq/app.js']) cp.execFileSync(process.execPath,['--check',f],{stdio:'inherit'});
const sandbox={window:{}};vm.createContext(sandbox);
for(const f of ['boq/data-01.js','boq/data-02.js']) vm.runInContext(fs.readFileSync(f,'utf8'),sandbox,{filename:f});
const text=zlib.gunzipSync(Buffer.from(sandbox.window.__FINANCE_B64||'','base64'),{finishFlush:zlib.constants.Z_SYNC_FLUSH}).toString('utf8');
const marker=',"plots":[';const i=text.indexOf(marker);if(i<0)throw new Error('plots marker not found');
const base=JSON.parse(text.slice(0,i)+',"plots":[]}');
console.log('RECOVERED_META='+JSON.stringify(base.meta));
console.log('RECOVERED_PORTFOLIOS='+JSON.stringify(base.portfolios));
console.log('RECOVERED_PROJECT_CODES='+JSON.stringify(base.projectCodes));
console.log('RECOVERED_WORK_TYPES='+JSON.stringify(base.workTypeLabels));
console.log('RECOVERED_YEAR_SUMMARY='+JSON.stringify(base.yearSummary));
throw new Error('metadata inspection complete; rebuild pending');
