(()=>{'use strict';
const D=window.PROJECT_DATA,$=id=>document.getElementById(id);if(!D){document.body.innerHTML='<p style="padding:40px">Missing dashboard data</p>';return}
const S={view:'overview',q:'',province:'',risk:'',follow:false};
const RL={critical:'วิกฤต',high:'เสี่ยงสูง',watch:'เฝ้าระวัง',on_track:'ตามแผน',ahead:'เร็วกว่าแผน'};
const PL={aligned:'สอดคล้องกับงาน',paid_ahead:'ERP นำหน้างาน',paid_behind:'ERP ต่ำกว่างาน',review:'ต้องตรวจ Voucher',no_data:'ยังไม่พบ ERP ปี 3'};
const CL={high:'ยืนยันได้',mixed:'มีรายการปนปี 2/3',none:'ไม่พบรายการปี 3'};
const esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const money=x=>new Intl.NumberFormat('th-TH',{maximumFractionDigits:0}).format(x||0),money2=x=>new Intl.NumberFormat('th-TH',{minimumFractionDigits:2,maximumFractionDigits:2}).format(x||0),pct=x=>`${((x||0)*100).toFixed(1)}%`;
const date=x=>x?new Intl.DateTimeFormat('th-TH',{day:'2-digit',month:'short',year:'2-digit'}).format(new Date(x+'T00:00:00')):'—';
const badge=(x,label)=>`<span class="badge ${x}">${label}</span>`,risk=p=>badge(p.risk,RL[p.risk]),payflag=p=>badge(p.paymentFlag,PL[p.paymentFlag]);
function conf(p){let c=p.payment.confidence,k=c==='high'?'high-confidence':c==='mixed'?'mixed-confidence':'none-confidence';return badge(k,CL[c])}
function paytext(p,short=false){let x=p.payment;if(x.confidence==='none')return short?'0%*':'0%* (ไม่พบรายการปี 3)';if(x.confidence==='mixed')return `${pct(x.confirmedPct)}–${pct(x.possiblePct)}`;return pct(x.confirmedPct)}
function rows(){let q=S.q.trim().toLowerCase();return D.plots.filter(p=>{if(S.province&&p.province!==S.province)return false;if(S.risk&&p.risk!==S.risk)return false;if(S.follow&&p.risk==='on_track'&&p.paymentFlag==='aligned'&&p.payment.confidence!=='mixed')return false;if(q&&!([p.plotId,p.contractNo,p.province,p.vendor,p.wo,p.workType].join(' ').toLowerCase().includes(q)))return false;return true})}
function kpi(a,b,c,cls=''){return `<article class="card kpi ${cls}"><div class="label">${a}</div><div class="value">${b}</div><div class="sub">${c}</div></article>`}
function bind(){document.querySelectorAll('[data-plot]').forEach(n=>n.onclick=()=>openPlot(n.dataset.plot))}
function overview(){let s=D.summary,v=rows(),top=[...v].sort((a,b)=>b.delayValue-a.delayValue).filter(p=>p.delayValue>0).slice(0,10),mx=Math.max(...top.map(p=>p.delayValue),1),ex=v.filter(p=>['paid_ahead','paid_behind','review'].includes(p.paymentFlag)).slice(0,8),rc=s.riskCounts,total=s.totalPlots||1;
$('overviewView').innerHTML=`<div class="kpi-grid">${kpi('มูลค่าสัญญารวม','฿'+money(s.totalContract),s.totalPlots+' แปลง / สัญญา')}${kpi('แผน ณ วันนี้',pct(s.plannedPct),'PV ฿'+money(s.plannedValue))}${kpi('งานทำได้จริง',pct(s.progressPct),'EV ฿'+money(s.earnedValue),'good')}${kpi('งานที่ขาดจากแผน','฿'+money(s.scheduleGapValue),'ช้ากว่าแผน '+s.scheduleGapPp.toFixed(1)+' จุด','alert')}${kpi('แปลงช้ากว่าแผน',s.delayedPlots,(rc.critical||0)+' วิกฤต + '+(rc.high||0)+' เสี่ยงสูง','alert')}${kpi('ERP ปี 3 ที่ Match ได้',s.paymentCoveragePlots+'/'+s.totalPlots,s.paymentHighConfidencePlots+' ยืนยันได้ · '+s.paymentMixedPlots+' ต้องตรวจ')}</div>
<div class="grid-2"><article class="card panel"><div class="panel-title-row"><div><h2>Plan vs Progress</h2><div class="panel-sub">มูลค่าสัญญารวม ฿${money(s.totalContract)}</div></div></div><div class="progress-comparison">${[['Plan',s.plannedPct,'plan'],['Progress',s.progressPct,''],['Gap',s.plannedPct-s.progressPct,'bad']].map(a=>`<div class="metric-row"><span>${a[0]}</span><div class="track"><div class="fill ${a[2]}" style="width:${Math.min(a[1]*100,100)}%"></div></div><b>${pct(a[1])}</b></div>`).join('')}</div></article>
<article class="card panel"><div class="panel-title-row"><div><h2>Risk Distribution</h2><div class="panel-sub">Gap % + จำนวนวันช้า</div></div></div><div class="risk-stack">${['critical','high','watch','on_track','ahead'].map(k=>`<div class="${k}" style="width:${((rc[k]||0)/total*100).toFixed(2)}%"></div>`).join('')}</div><div class="legend">${['critical','high','watch','on_track','ahead'].filter(k=>rc[k]).map(k=>`<span><i class="dot ${k}"></i>${RL[k]} ${rc[k]}</span>`).join('')}</div><div class="callout" style="margin-top:16px">Critical: gap ≥25 จุด หรือ ≥90 วัน · High: gap ≥10 จุด หรือ ≥30 วัน</div></article></div>
<div class="grid-2"><article class="card panel"><div class="panel-title-row"><div><h2>Top 10 มูลค่างานที่ช้ากว่าแผน</h2><div class="panel-sub">Plan Value − Earned Value</div></div></div><div class="bar-list">${top.map(p=>`<div class="bar-row clickable" data-plot="${p.plotId}"><span class="name">${p.plotId}</span><div class="bar-bg"><div class="bar-value" style="width:${p.delayValue/mx*100}%"></div></div><span class="bar-amount">฿${money(p.delayValue)}</span></div>`).join('')||'<div class="empty">ไม่มีรายการ</div>'}</div></article>
<article class="card panel"><div class="panel-title-row"><div><h2>Payment Exceptions</h2><div class="panel-sub">ERP ต่างจาก Progress หรือ voucher ปนปี</div></div></div><div class="table-wrap" style="max-height:360px"><table style="min-width:620px"><thead><tr><th>แปลง</th><th>Progress</th><th>ERP</th><th>สถานะ</th></tr></thead><tbody>${ex.map(p=>`<tr class="clickable" data-plot="${p.plotId}"><td><b>${p.plotId}</b><div class="small muted">${esc(p.contractNo)}</div></td><td>${pct(p.progressPct)}</td><td>${paytext(p,true)}</td><td>${payflag(p)}</td></tr>`).join('')}</tbody></table></div></article></div>
<article class="callout info"><b>เงิน:</b> ใช้ AP posting ที่ remark ระบุ “ปีที่3”. รายการที่ปน “ปีที่2 + ปีที่3” แสดงเป็นช่วงแทนการเดา allocation; ยังไม่ใช่ cash clearing จากธนาคาร.</article>`;bind()}
function schedule(){let r=rows().sort((a,b)=>b.delayValue-a.delayValue||b.scheduleGapPp-a.scheduleGapPp);$('scheduleView').innerHTML=`<article class="card table-card"><div class="table-toolbar"><div><h2>ติดตาม Progress รายแปลง / สัญญา</h2><div class="table-meta">${r.length} รายการ · เรียงมูลค่างานช้าสูงสุดก่อน</div></div></div><div class="table-wrap"><table><thead><tr><th>แปลง</th><th>สัญญา / WO</th><th class="num">มูลค่าสัญญา</th><th>Plan</th><th>Progress</th><th class="num">Gap</th><th class="num">ช้า</th><th class="num">มูลค่างานช้า</th><th>Risk</th></tr></thead><tbody>${r.map(p=>{let g=p.progressPct-p.planPct;return `<tr class="clickable" data-plot="${p.plotId}"><td><div class="main-cell">${p.plotId}</div><div class="small muted">${esc(p.province)} · ${p.areaRai?money2(p.areaRai)+' ไร่':'—'}</div></td><td>${esc(p.contractNo||'—')}<div class="small muted">${esc(p.wo||'')}</div></td><td class="num">฿${money(p.contractValue)}</td><td>${pct(p.planPct)}</td><td>${pct(p.progressPct)}</td><td class="num ${g<0?'delta-negative':''}">${g>=0?'+':''}${(g*100).toFixed(1)} pp</td><td class="num">${p.delayDays<0?Math.abs(p.delayDays).toFixed(1)+' วัน':'—'}</td><td class="num">${p.delayValue?'฿'+money(p.delayValue):'—'}</td><td>${risk(p)}</td></tr>`}).join('')}</tbody></table></div></article><div class="footer-note">คลิกแถวเพื่อดูงวดงานและ ERP ของสัญญา</div>`;bind()}
function payments(){let order={paid_ahead:0,paid_behind:1,review:2,aligned:3,no_data:4},r=rows().sort((a,b)=>order[a.paymentFlag]-order[b.paymentFlag]||b.contractValue-a.contractValue);$('paymentsView').innerHTML=`<div class="grid-2"><article class="card panel"><div class="panel-title-row"><div><h2>ERP Payment Coverage</h2><div class="panel-sub">${D.summary.paymentCoveragePlots}/${D.summary.totalPlots} แปลงมีรายการปี 3</div></div></div><div class="detail-grid" style="grid-template-columns:repeat(3,1fr)"><div class="detail-item"><div class="label">ยืนยันได้</div><div class="value">${D.summary.paymentHighConfidencePlots}</div></div><div class="detail-item"><div class="label">ปนปี 2/3</div><div class="value">${D.summary.paymentMixedPlots}</div></div><div class="detail-item"><div class="label">ไม่พบปี 3</div><div class="value">${D.summary.paymentNoRecordPlots}</div></div></div></article><article class="card panel"><div class="panel-title-row"><div><h2>ยอด ERP ปี 3</h2></div></div><div class="detail-grid" style="grid-template-columns:1fr 1fr"><div class="detail-item"><div class="label">ยืนยันได้</div><div class="value">฿${money(D.summary.confirmedErpAmount)} (${pct(D.summary.confirmedErpPctOfPortfolio)})</div></div><div class="detail-item"><div class="label">รวม mixed สูงสุด</div><div class="value">${pct(D.summary.possibleErpPctOfPortfolio)}</div></div></div></article></div>
<article class="card table-card"><div class="table-toolbar"><div><h2>สถานะเงินรายสัญญา</h2><div class="table-meta">0%* = ไม่พบ AP ที่ระบุปีที่ 3</div></div></div><div class="table-wrap"><table style="min-width:1320px"><thead><tr><th>แปลง</th><th>สัญญา / WO</th><th>ผู้รับเหมา</th><th class="num">สัญญา</th><th class="num">Progress</th><th class="num">ERP ปี 3</th><th>สถานะเงิน</th><th>คุณภาพ</th><th>ERP ล่าสุด</th></tr></thead><tbody>${r.map(p=>`<tr class="clickable" data-plot="${p.plotId}"><td><b>${p.plotId}</b><div class="small muted">${esc(p.province)}</div></td><td>${esc(p.contractNo||'—')}<div class="small muted">${esc(p.wo||'')}</div></td><td>${esc(p.vendor||'—')}</td><td class="num">฿${money(p.contractValue)}</td><td class="num">${pct(p.progressPct)}</td><td class="num"><b>${paytext(p,true)}</b></td><td>${payflag(p)}</td><td>${conf(p)}</td><td>${date(p.payment.lastDate)}</td></tr>`).join('')}</tbody></table></div></article>`;bind()}
function quality(){let s=D.summary,m=D.meta;$('qualityView').innerHTML=`<div class="quality-grid"><article class="card quality-card"><div class="caption">Plot → Contract mapping</div><div class="big">${s.totalPlots}/${s.totalPlots}</div><div class="caption">Exact Plot ID รวม suffix (1)</div></article><article class="card quality-card"><div class="caption">ERP ปี 3 ยืนยันได้</div><div class="big">${s.paymentHighConfidencePlots}</div></article><article class="card quality-card"><div class="caption">Voucher ต้องตรวจ</div><div class="big">${s.paymentMixedPlots}</div><div class="caption">ข้อความปี 2 + ปี 3 ปนกัน</div></article><article class="card quality-card"><div class="caption">ERP duplicate sheet</div><div class="big">${m.erpSecondSheetDuplicate?'ข้ามแล้ว':'ตรวจสอบ'}</div></article></div><article class="card panel"><div class="panel-title-row"><div><h2>Data Rules</h2></div></div><ol class="rule-list"><li>รวม KPI จากแถวระดับ Plot เท่านั้น ทำให้ยอดสัญญาตรง Project Header ฿${money(s.totalContract)}</li><li>Contract, WO, Vendor map ด้วย Plot ID แบบ exact เช่น 14-STC ≠ 14(1)-STC</li><li>มุมเงินใช้ module=AP; GL ค่าใช้จ่ายภายในไม่รวมเป็น payment contractor</li><li>Voucher ปนปี 2/3 แยกเป็น ambiguous ไม่ force allocate</li><li>Ranking งานใช้ Delay Value = Plan ฿ − Progress ฿</li></ol></article><div class="callout info" style="margin-top:16px">Progress ${date(m.progressAsOf)} · ERP transaction ล่าสุด ${date(m.erpMaxTransactionDate)} · Raw Excel ไม่ถูก commit.</div>`}
function render(){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.view===S.view));$(S.view+'View').classList.add('active');({overview,schedule,payments,quality}[S.view])()}
function openPlot(id){let p=D.plots.find(x=>x.plotId===id);if(!p)return;let x=p.payment,g=p.progressPct-p.planPct,inst=p.installments.map(i=>`<div class="installment"><b>งวด ${i.no}</b><div><b>งวดที่ ${i.no}</b><div class="small muted">${esc(i.startDate||'—')} → ${esc(i.endDate||'—')} · ฿${money(i.contractValue)}</div></div><div>Plan <b>${pct(i.planPct)}</b></div><div>Progress <b>${pct(i.progressPct)}</b></div></div>`).join(''),rec=x.records.length?x.records.map(r=>`<div class="payment-record"><div>${date(r.date)}</div><div><b>${esc(r.voucher||'—')}</b></div><div class="num">฿${money2(r.amount)}</div><div><span class="badge ${r.quality==='mixed_year'?'review':'aligned'}">${r.quality==='mixed_year'?'ปนปี 2/3':'ปี 3'}</span></div></div>`).join(''):'<div class="empty">ไม่พบ AP transaction ที่ระบุปีที่ 3</div>';
$('modalContent').innerHTML=`<header class="modal-head"><div class="eyebrow" style="color:var(--green)">PLOT / CONTRACT DETAIL</div><h2 id="modalTitle">${p.plotId} · ${esc(p.province)}</h2><div class="muted">${esc(p.contractNo||'—')} · ${esc(p.vendor||'—')}</div></header><div class="modal-body"><div class="detail-grid"><div class="detail-item"><div class="label">มูลค่าสัญญา</div><div class="value">฿${money2(p.contractValue)}</div></div><div class="detail-item"><div class="label">WO</div><div class="value">${esc(p.wo||'—')}</div></div><div class="detail-item"><div class="label">พื้นที่</div><div class="value">${p.areaRai?money2(p.areaRai)+' ไร่':'—'}</div></div><div class="detail-item"><div class="label">Risk</div><div class="value">${risk(p)}</div></div></div><div class="dual-progress"><div class="progress-box"><div class="topline"><span>Plan</span><b>${pct(p.planPct)}</b></div><div class="track"><div class="fill plan" style="width:${p.planPct*100}%"></div></div><div class="small muted" style="margin-top:8px">PV ฿${money2(p.planValue)}</div></div><div class="progress-box"><div class="topline"><span>Progress</span><b>${pct(p.progressPct)}</b></div><div class="track"><div class="fill" style="width:${p.progressPct*100}%"></div></div><div class="small ${g<0?'delta-negative':'muted'}" style="margin-top:8px">EV ฿${money2(p.progressValue)} · Gap ${g>=0?'+':''}${(g*100).toFixed(1)} pp ${p.delayDays<0?'· ช้า '+Math.abs(p.delayDays).toFixed(1)+' วัน':''}</div></div></div><section><h3>งวดงาน</h3><div class="installment-grid" style="margin-top:10px">${inst}</div></section><section><h3>ERP ปีที่ 3</h3><div class="panel-sub" style="margin:5px 0 10px">${paytext(p)} · ${payflag(p)} · ${conf(p)}</div><div class="detail-grid" style="grid-template-columns:repeat(3,1fr);margin-bottom:8px"><div class="detail-item"><div class="label">ยอดยืนยัน</div><div class="value">฿${money2(x.confirmedAmount)} (${pct(x.confirmedPct)})</div></div><div class="detail-item"><div class="label">ยอดปนปี 2/3</div><div class="value">฿${money2(x.ambiguousAmount)}</div></div><div class="detail-item"><div class="label">ERP ล่าสุด</div><div class="value">${date(x.lastDate)}</div></div></div>${rec}</section><div class="callout info">ERP = AP posting จาก export ที่ให้มา ไม่ใช่หลักฐาน cash clearing.</div></div>`;$('modalBackdrop').hidden=false;document.body.style.overflow='hidden'}
function close(){ $('modalBackdrop').hidden=true;document.body.style.overflow='' }
function csv(){let h=['Plot','Province','Contract No','WO','Vendor','Contract Value','Plan %','Progress %','Gap pp','Delay Days','Delay Value','Risk','ERP Confirmed %','ERP Possible %','Payment Confidence','Payment Flag','ERP Last Date'],v=rows().map(p=>[p.plotId,p.province,p.contractNo,p.wo,p.vendor,p.contractValue,p.planPct,p.progressPct,p.scheduleGapPp,p.delayDays,p.delayValue,p.risk,p.payment.confirmedPct,p.payment.possiblePct,p.payment.confidence,p.paymentFlag,p.payment.lastDate]),t=[h,...v].map(r=>r.map(z=>`"${String(z??'').replace(/"/g,'""')}"`).join(',')).join('\n'),b=new Blob(['\ufeff'+t],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='forest-project-dashboard.csv';a.click();URL.revokeObjectURL(a.href)}
$('.tab');document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{S.view=t.dataset.view;render()});$('searchInput').oninput=e=>{S.q=e.target.value;render()};$('provinceFilter').onchange=e=>{S.province=e.target.value;render()};$('riskFilter').onchange=e=>{S.risk=e.target.value;render()};$('followupOnly').onchange=e=>{S.follow=e.target.checked;render()};$('resetFilters').onclick=()=>{S.q=S.province=S.risk='';S.follow=false;$('searchInput').value=$('provinceFilter').value=$('riskFilter').value='';$('followupOnly').checked=false;render()};$('exportCsv').onclick=csv;$('modalClose').onclick=close;$('modalBackdrop').onclick=e=>{if(e.target===$('modalBackdrop'))close()};document.onkeydown=e=>{if(e.key==='Escape')close()};
$('asOf').innerHTML=`Progress: <b>${date(D.meta.progressAsOf)}</b><br>ERP ล่าสุด: <b>${date(D.meta.erpMaxTransactionDate)}</b>`;$('provinceFilter').innerHTML='<option value="">ทั้งหมด</option>'+[...new Set(D.plots.map(p=>p.province))].sort((a,b)=>a.localeCompare(b,'th')).map(x=>`<option>${esc(x)}</option>`).join('');render();
})();
