(()=>{'use strict';
const $=id=>document.getElementById(id);const STORAGE_KEY='contract-submission-projects-v1';
const S={projects:[],activeId:null,editingId:null,mode:'hub',q:'',projectYear:'',workYear:'',province:'',installment:'',status:'',quality:[],conflicts:[]};
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const uid=()=>globalThis.crypto?.randomUUID?.()||`p-${Date.now()}-${Math.random().toString(36).slice(2)}`;
const normalize=v=>String(v??'').trim().replace(/\s+/g,' ').toLocaleLowerCase('th');
function runtimeProject(x){return {id:String(x.id),name:String(x.name),note:String(x.note||''),createdAt:Number(x.createdAt)||Date.now(),files:[]}}
function loadProjects(){try{const raw=JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]');if(Array.isArray(raw))S.projects=raw.filter(x=>x?.id&&x?.name).map(runtimeProject)}catch(e){console.warn(e)}}
function persistProjects(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(S.projects.map(({id,name,note,createdAt})=>({id,name,note,createdAt}))))}catch(e){console.warn(e)}}
function project(id=S.activeId){return S.projects.find(p=>p.id===id)||null}
function fileCount(p){return p?.files?.length||0}
function parsedPlots(p){return p?.files?.reduce((n,f)=>n+f.parsed.recognized.reduce((s,r)=>s+r.plots.length,0),0)||0}
function projectYears(p){return [...new Set((p?.files||[]).flatMap(f=>f.parsed.recognized.map(r=>r.projectYear).filter(Boolean)))].sort()}
function workYears(p){return [...new Set((p?.files||[]).flatMap(f=>f.parsed.recognized.map(r=>String(r.workYear||'')).filter(Boolean)))].sort((a,b)=>Number(a)-Number(b))}
function projectStatus(p){if(!p||!fileCount(p))return 'ยังไม่มี Excel';return `${fileCount(p)} ไฟล์ · ${workYears(p).length} ปีงาน · ${parsedPlots(p).toLocaleString('th-TH')} แปลงก่อนรวมซ้ำ`}
function renderSelector(){const sel=$('projectSelect'),arr=[...S.projects].sort((a,b)=>a.createdAt-b.createdAt);sel.disabled=!arr.length;sel.innerHTML=`<option value="">${arr.length?'เลือกโครงการ…':'ยังไม่มีโครงการ'}</option>`+arr.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('');sel.value=S.activeId||'';$('showProjectsBtn').disabled=!arr.length}
function renderHero(){const p=project();$('heroSummary').innerHTML=p?`โครงการที่กำลังดู<br><b>${esc(p.name)}</b><br><small>${esc(projectStatus(p))}</small>`:`ยังไม่ได้เลือกโครงการ<br><b>${S.projects.length} โครงการในรายการ</b>`}
function renderCards(){const c=$('projectCards');if(!S.projects.length){c.innerHTML=`<button class="project-add-card" data-action="add" type="button"><span>＋</span><strong>สร้างโครงการแรก</strong><small>ตั้งชื่อก่อน แล้วค่อยเพิ่ม Excel</small></button>`;bindProjectActions();return}c.innerHTML=[...S.projects].sort((a,b)=>a.createdAt-b.createdAt).map(p=>`<article class="project-card ${p.id===S.activeId?'active':''}"><div class="project-card-top"><span class="project-mark">PROJECT</span><span class="small">${new Date(p.createdAt).toLocaleDateString('th-TH')}</span></div><h3>${esc(p.name)}</h3><p>${esc(p.note||'ยังไม่ได้ระบุรายละเอียด')}</p><div class="project-card-facts">${fileCount(p)?`<span>${fileCount(p)} Excel</span><span>${workYears(p).length} ปีงาน</span><span>${parsedPlots(p)} แปลง</span>`:'<span>รอเพิ่ม Excel</span>'}</div><button class="project-open" data-action="open" data-project="${esc(p.id)}" type="button">เปิดโครงการ</button></article>`).join('')+`<button class="project-add-card" data-action="add" type="button"><span>＋</span><strong>เพิ่มโครงการ</strong><small>สร้างชุด Excel แยกอีกชุด</small></button>`;bindProjectActions()}
function bindProjectActions(){document.querySelectorAll('[data-action="add"]').forEach(b=>b.onclick=()=>openProjectModal());document.querySelectorAll('[data-action="open"]').forEach(b=>b.onclick=()=>selectProject(b.dataset.project))}
function renderWorkspace(){const p=project();if(!p)return;$('activeProjectName').textContent=p.name;$('activeProjectNote').textContent=p.note||'ชุด Excel ของโครงการนี้แยกจากโครงการอื่น';$('workspaceStatus').textContent=projectStatus(p);renderFileManager();rebuild()}
function renderAll(){renderSelector();renderHero();renderCards();if(project())renderWorkspace()}
function setMode(mode){S.mode=mode;$('projectHub').hidden=mode!=='hub';$('workspace').hidden=mode!=='workspace';renderAll()}
function showHub(){S.activeId=null;resetFilters();document.title='Contract Submission Monitor · Project Hub';setMode('hub')}
function selectProject(id){if(!project(id))return;S.activeId=id;resetFilters();document.title=`${project(id).name} · Contract Submission Monitor`;setMode('workspace')}
function openProjectModal(id=null){S.editingId=id;const p=project(id);$('projectModalTitle').textContent=p?'แก้ไขโครงการ':'เพิ่มโครงการ';$('projectNameInput').value=p?.name||'';$('projectNoteInput').value=p?.note||'';$('projectFormError').textContent='';$('projectModal').hidden=false;document.body.style.overflow='hidden';setTimeout(()=>$('projectNameInput').focus(),0)}
function closeProjectModal(){$('projectModal').hidden=true;document.body.style.overflow=''}
function saveProject(){const name=$('projectNameInput').value.trim(),note=$('projectNoteInput').value.trim();if(!name){$('projectFormError').textContent='กรุณาใส่ชื่อโครงการ';return}if(S.projects.some(p=>p.id!==S.editingId&&normalize(p.name)===normalize(name))){$('projectFormError').textContent='มีชื่อโครงการนี้แล้ว';return}if(S.editingId){const p=project(S.editingId);p.name=name;p.note=note}else{const p=runtimeProject({id:uid(),name,note,createdAt:Date.now()});S.projects.push(p);S.activeId=p.id}persistProjects();closeProjectModal();if(S.activeId)setMode('workspace');else renderAll()}
function deleteCurrentProject(){const p=project();if(!p)return;if(!confirm(`ลบโครงการ “${p.name}” ออกจากรายการ?`))return;S.projects=S.projects.filter(x=>x.id!==p.id);persistProjects();showHub()}
function formatSize(n){if(n<1024)return `${n} B`;if(n<1048576)return `${(n/1024).toFixed(1)} KB`;return `${(n/1048576).toFixed(1)} MB`}
async function addFiles(list){const p=project(),files=[...(list||[])];if(!p||!files.length)return;for(const file of files){try{if(p.files.some(x=>x.name===file.name&&x.size===file.size&&x.lastModified===file.lastModified))continue;const buf=await file.arrayBuffer();const wb=XLSX.read(buf,{type:'array',cellDates:true});const parsed=ContractSubmissionParser.parseWorkbook(wb,file.name);p.files.push({id:uid(),name:file.name,size:file.size,lastModified:file.lastModified,addedAt:Date.now(),parsed})}catch(error){alert(`${file.name}\n${error.message||error}`)}}renderFileManager();rebuild();renderHero();renderCards()}
function removeFile(id){const p=project();if(!p)return;p.files=p.files.filter(f=>f.id!==id);renderFileManager();rebuild();renderHero();renderCards()}
function renderFileManager(){const p=project();if(!p)return;const count=fileCount(p);$('fileSummary').textContent=count?`${count} ไฟล์ · ${projectYears(p).map(y=>'พ.ศ. '+y).join(', ')||'ไม่พบปีโครงการ'} · ปีที่ ${workYears(p).join(', ')||'—'}`:'ยังไม่มีไฟล์';$('qualityBtn').disabled=!count;$('fileList').innerHTML=p.files.map(f=>{const recognized=f.parsed.recognized,plots=recognized.reduce((s,r)=>s+r.plots.length,0);return `<div class="file-card"><div class="file-card-main"><strong title="${esc(f.name)}">${esc(f.name)}</strong><small>${formatSize(f.size)} · ${plots} แปลง · ${recognized.length} sheet ที่อ่านได้</small><div class="file-tags">${recognized.map(r=>`<span>พ.ศ. ${esc(r.projectYear||'?')} · ปีที่ ${esc(r.workYear||'?')}</span>`).join('')}</div></div><button class="icon-btn danger" data-remove-file="${esc(f.id)}" type="button" title="ลบไฟล์">×</button></div>`}).join('');document.querySelectorAll('[data-remove-file]').forEach(b=>b.onclick=()=>removeFile(b.dataset.removeFile))}
function mergedData(){const p=project();if(!p)return {plots:[],rows:[],quality:[],conflicts:[]};const plotMap=new Map(),quality=[],conflicts=[];for(const f of p.files){for(const sk of f.parsed.skipped||[])quality.push({file:f.name,type:'skipped',text:`ข้าม sheet “${sk.sheetName}”: ${sk.error}`});for(const rec of f.parsed.recognized){(rec.warnings||[]).forEach(w=>quality.push({file:f.name,type:'warning',text:`${rec.sheetName}: ${w}`}));for(const plot of rec.plots){const key=`${rec.projectYear}|${rec.workYear}|${plot.plotId}`;if(plotMap.has(key))conflicts.push(`พ.ศ. ${rec.projectYear} ปีที่ ${rec.workYear} · ${plot.plotId}: ใช้ข้อมูลจากไฟล์ที่เพิ่มล่าสุด (${f.name})`);plotMap.set(key,{...plot,projectYear:String(rec.projectYear||''),workYear:String(rec.workYear||''),sourceFile:f.name,sourceSheet:rec.sheetName})}}}const plots=[...plotMap.values()],rows=[];for(const p of plots)for(const i of p.installments)rows.push({...p,installment:i.no,rowStatus:i.status,statusLabel:i.label,submissionRaw:i.raw,submissionDate:i.date,future:i.future});return {plots,rows,quality,conflicts}}
function resetFilters(){S.q=S.projectYear=S.workYear=S.province=S.installment=S.status='';for(const id of ['search','projectYear','workYear','province','installment','status'])if($(id))$(id).value=''}
function fillSelect(id,values,prefix=''){const el=$(id),current=el.value;const first=id==='installment'?'<option value="">ทุกงวด</option>':'<option value="">ทั้งหมด</option>';el.innerHTML=first+values.map(v=>`<option value="${esc(v)}">${prefix}${esc(v)}</option>`).join('');if(values.includes(current))el.value=current}
function rebuild(){const p=project();const has=!!fileCount(p);$('emptyDashboard').hidden=has;$('dashboard').hidden=!has;if(!has){S.quality=[];S.conflicts=[];return}const d=mergedData();S.quality=d.quality;S.conflicts=d.conflicts;fillSelect('projectYear',[...new Set(d.plots.map(x=>x.projectYear).filter(Boolean))].sort(),'พ.ศ. ');fillSelect('workYear',[...new Set(d.plots.map(x=>x.workYear).filter(Boolean))].sort((a,b)=>Number(a)-Number(b)),'ปีที่ ');fillSelect('province',[...new Set(d.plots.map(x=>x.province).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'th')));fillSelect('installment',[...new Set(d.rows.map(x=>String(x.installment)))].sort((a,b)=>Number(a)-Number(b)),'งวดที่ ');$('projectYear').value=S.projectYear;$('workYear').value=S.workYear;$('province').value=S.province;$('installment').value=S.installment;$('status').value=S.status;renderDashboard(d)}
function filteredRows(d){const q=S.q.trim().toLocaleLowerCase('th');return d.rows.filter(r=>(!S.projectYear||r.projectYear===S.projectYear)&&(!S.workYear||r.workYear===S.workYear)&&(!S.province||r.province===S.province)&&(!S.installment||String(r.installment)===S.installment)&&(!S.status||r.rowStatus===S.status)&&(!q||[r.plotId,r.province,r.company,r.contractNo,r.contractGroup,r.sourceFile].join(' ').toLocaleLowerCase('th').includes(q)))}
function statusBadge(r){return `<span class="status-badge status-${r.rowStatus}">${esc(r.statusLabel)}</span>${r.future?'<span class="future-flag">Future date</span>':''}`}
function renderDashboard(d){const rows=filteredRows(d),plotKeys=new Set(rows.map(r=>`${r.projectYear}|${r.workYear}|${r.plotId}`)),submitted=rows.filter(r=>r.rowStatus==='submitted').length,pending=rows.filter(r=>r.rowStatus==='pending').length,stopped=rows.filter(r=>['suspended','terminated'].includes(r.rowStatus)).length,na=rows.filter(r=>r.rowStatus==='na').length,future=rows.filter(r=>r.future).length;const totalActionable=submitted+pending+stopped;const rate=totalActionable?submitted/totalActionable*100:0;$('kpis').innerHTML=kpi('แปลงในผลกรอง',plotKeys.size,`จาก ${d.plots.length} แปลงหลังรวมไฟล์`)+kpi('งวดที่ส่งแล้ว',submitted,`${rate.toFixed(1)}% ของงวดที่เกี่ยวข้อง`,'good')+kpi('งวดค้างส่ง',pending,'ช่องว่าง/ข้อความที่ไม่ใช่วันที่','warn')+kpi('ชะลอ / ยุติ',stopped,'ไม่นับเป็น Submitted','bad')+kpi('N/A',na,'เกินจำนวนงวดตามกลุ่มสัญญา')+kpi('Future date',future,'วันที่หลังวันปัจจุบัน','warn');renderInstallments(rows);renderProvinces(rows);renderTable(rows,d)}
function kpi(label,value,sub,cls=''){return `<article class="card kpi ${cls}"><div class="label">${label}</div><div class="value">${Number(value).toLocaleString('th-TH')}</div><div class="sub">${sub}</div></article>`}
function renderInstallments(rows){const g=new Map();for(const r of rows){const key=`${r.projectYear}|${r.workYear}|${r.installment}`,x=g.get(key)||{projectYear:r.projectYear,workYear:r.workYear,no:r.installment,submitted:0,pending:0,stopped:0,na:0,total:0};x.total++;if(r.rowStatus==='submitted')x.submitted++;else if(r.rowStatus==='pending')x.pending++;else if(['suspended','terminated'].includes(r.rowStatus))x.stopped++;else x.na++;g.set(key,x)}const a=[...g.values()].sort((x,y)=>Number(x.projectYear)-Number(y.projectYear)||Number(x.workYear)-Number(y.workYear)||x.no-y.no);$('installmentSummary').innerHTML=a.length?a.map(x=>{const den=x.total||1;return `<div class="inst-row" data-inst="${x.no}"><div class="inst-head"><strong>พ.ศ. ${esc(x.projectYear||'?')} · ปีที่ ${esc(x.workYear||'?')} · งวด ${x.no}</strong><span class="inst-counts">ส่ง ${x.submitted} · ค้าง ${x.pending} · หยุด ${x.stopped}${x.na?` · N/A ${x.na}`:''}</span></div><div class="stackbar"><i class="seg-submitted" style="width:${x.submitted/den*100}%"></i><i class="seg-pending" style="width:${x.pending/den*100}%"></i><i class="seg-stopped" style="width:${x.stopped/den*100}%"></i><i class="seg-na" style="width:${x.na/den*100}%"></i></div></div>`}).join(''):'<div class="empty">ไม่พบข้อมูล</div>'}
function renderProvinces(rows){const g={};for(const r of rows){if(r.rowStatus==='na')continue;const x=g[r.province]||(g[r.province]={total:0,pending:0,stopped:0});x.total++;if(r.rowStatus==='pending')x.pending++;if(['suspended','terminated'].includes(r.rowStatus))x.stopped++}const a=Object.entries(g).sort((a,b)=>b[1].pending-a[1].pending||b[1].stopped-a[1].stopped).slice(0,18);$('provinceSummary').innerHTML=a.length?a.map(([name,x])=>`<div class="province-item" data-prov="${esc(name)}"><div class="province-top"><span>${esc(name||'ไม่ระบุ')}</span><span>${x.pending} ค้างส่ง</span></div><small>${x.stopped?`${x.stopped} งวดชะลอ/ยุติ · `:''}${x.total} งวดที่เกี่ยวข้อง</small><div class="mini-track"><i style="width:${x.total?x.pending/x.total*100:0}%"></i></div></div>`).join(''):'<div class="empty">ไม่พบข้อมูล</div>';document.querySelectorAll('[data-prov]').forEach(e=>e.onclick=()=>{S.province=e.dataset.prov;$('province').value=S.province;renderDashboard(mergedData())})}
function renderTable(rows,d){const sorted=[...rows].sort((a,b)=>Number(a.projectYear)-Number(b.projectYear)||Number(a.workYear)-Number(b.workYear)||a.plotId.localeCompare(b.plotId,'th',{numeric:true})||a.installment-b.installment);$('tableMeta').textContent=`${sorted.length.toLocaleString('th-TH')} แถวสถานะ · คลิกแถวเพื่อดูทุกงวดของแปลง`;$('submissionRows').innerHTML=sorted.length?sorted.map(r=>`<tr data-detail-key="${esc(`${r.projectYear}|${r.workYear}|${r.plotId}`)}"><td><div class="plot-id">${esc(r.plotId)}</div><div class="small">${esc(r.contractGroup||'')}</div></td><td>${esc(r.province||'—')}</td><td>${esc(r.company||'—')}</td><td>${esc(r.contractNo||'—')}</td><td>${esc(r.projectYear||'—')}</td><td>${esc(r.workYear||'—')}</td><td>งวด ${r.installment}</td><td>${statusBadge(r)}</td><td>${esc(r.submissionRaw||'—')}</td><td><span class="source-chip" title="${esc(r.sourceFile)}">${esc(r.sourceFile)}</span></td></tr>`).join(''):'<tr><td colspan="10"><div class="empty">ไม่พบรายการตามตัวกรอง</div></td></tr>';document.querySelectorAll('[data-detail-key]').forEach(tr=>tr.onclick=()=>openDetail(tr.dataset.detailKey,d))}
function openDetail(key,d){const [py,wy,pid]=key.split('|'),p=d.plots.find(x=>x.projectYear===py&&x.workYear===wy&&x.plotId===pid);if(!p)return;$('detailContent').innerHTML=`<div class="modal-head"><div class="eyebrow">PLOT DETAIL · ROK → ผรม.</div><h2>${esc(p.plotId)} · ${esc(p.province||'')}</h2><p>${esc(p.sourceFile)} · ${esc(p.sourceSheet)}</p></div><div class="modal-body"><div class="detail-grid"><div class="detail-box"><span>ปีโครงการ</span><strong>พ.ศ. ${esc(p.projectYear||'—')}</strong></div><div class="detail-box"><span>ปีดำเนินงาน</span><strong>ปีที่ ${esc(p.workYear||'—')}</strong></div><div class="detail-box"><span>สัญญา TC–ROK</span><strong>${esc(p.contractNo||'—')}</strong></div><div class="detail-box"><span>เนื้อที่สัญญา</span><strong>${p.contractArea!=null?`${Number(p.contractArea).toLocaleString('th-TH')} ไร่`:'—'}</strong></div></div><div class="detail-grid"><div class="detail-box"><span>บริษัท</span><strong>${esc(p.company||'—')}</strong></div><div class="detail-box"><span>อำเภอ</span><strong>${esc(p.district||'—')}</strong></div><div class="detail-box"><span>ผู้ตรวจงาน</span><strong>${esc(p.inspector||'—')}</strong></div><div class="detail-box"><span>กลุ่มสัญญา</span><strong>${esc(p.contractGroup||'—')}</strong></div></div><section><h3>สถานะการส่งงาน ผรม.</h3><div class="detail-installments">${p.installments.map(i=>`<div class="detail-inst"><strong>งวด ${i.no}</strong><div><span class="status-badge status-${i.status}">${esc(i.label)}</span>${i.future?'<span class="future-flag">Future date</span>':''}</div><div>${esc(i.raw||'—')}</div></div>`).join('')}</div></section></div>`;$('detailModal').hidden=false;document.body.style.overflow='hidden'}
function openQuality(){const p=project();if(!p)return;const fileGroups=p.files.map(f=>{const warnings=[];(f.parsed.skipped||[]).forEach(x=>warnings.push(`ข้าม sheet “${x.sheetName}”: ${x.error}`));f.parsed.recognized.forEach(r=>(r.warnings||[]).forEach(w=>warnings.push(`${r.sheetName}: ${w}`)));return `<div class="quality-group"><h3>${esc(f.name)}</h3>${warnings.length?`<ul class="quality-list">${warnings.map(w=>`<li>${esc(w)}</li>`).join('')}</ul>`:'<p class="small">ไม่พบ warning จาก parser</p>'}</div>`}).join('');$('qualityContent').innerHTML=`<div class="modal-head"><div class="eyebrow">DATA QUALITY</div><h2>ผลตรวจไฟล์ในโครงการ</h2><p>ระบบไม่นับข้อความที่ไม่ใช่วันที่เป็น “ส่งแล้ว” และแจ้ง duplicate/future date</p></div><div class="modal-body">${S.conflicts.length?`<div class="quality-group"><h3>ข้อมูลซ้ำระหว่างไฟล์</h3><ul class="quality-list">${S.conflicts.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`:''}${fileGroups}</div>`;$('qualityModal').hidden=false;document.body.style.overflow='hidden'}
function exportCsv(){const d=mergedData(),rows=filteredRows(d);const headers=['ปีโครงการ','ปีที่','รหัสแปลง','จังหวัด','บริษัท','เลขสัญญา TC-ROK','งวด','สถานะ','วันที่/ข้อความ','Future date','ไฟล์','Sheet'];const data=rows.map(r=>[r.projectYear,r.workYear,r.plotId,r.province,r.company,r.contractNo,r.installment,r.statusLabel,r.submissionRaw,r.future?'YES':'',r.sourceFile,r.sourceSheet]);const csv=[headers,...data].map(row=>row.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')).join('\r\n');const blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`contract-submission-${project()?.name||'project'}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function bind(){
  $('addProjectBtn').onclick=()=>openProjectModal();$('showProjectsBtn').onclick=showHub;$('switchProjectBtn').onclick=showHub;$('editProjectBtn').onclick=()=>openProjectModal(S.activeId);$('deleteProjectBtn').onclick=deleteCurrentProject;$('projectSelect').onchange=e=>e.target.value?selectProject(e.target.value):showHub();
  $('projectModalClose').onclick=$('projectCancel').onclick=closeProjectModal;$('projectSave').onclick=saveProject;$('projectModal').onclick=e=>{if(e.target===$('projectModal'))closeProjectModal()};
  $('addFilesBtn').onclick=()=>$('excelInput').click();$('excelInput').onchange=e=>{addFiles(e.target.files);e.target.value=''};const dz=$('dropzone');['dragenter','dragover'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.add('dragover')}));['dragleave','drop'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.remove('dragover')}));dz.addEventListener('drop',e=>addFiles(e.dataTransfer.files));
  $('qualityBtn').onclick=openQuality;$('qualityClose').onclick=()=>{$('qualityModal').hidden=true;document.body.style.overflow=''};$('detailClose').onclick=()=>{$('detailModal').hidden=true;document.body.style.overflow=''};[$('qualityModal'),$('detailModal')].forEach(m=>m.onclick=e=>{if(e.target===m){m.hidden=true;document.body.style.overflow=''}});
  $('search').oninput=e=>{S.q=e.target.value;renderDashboard(mergedData())};for(const [id,key] of [['projectYear','projectYear'],['workYear','workYear'],['province','province'],['installment','installment'],['status','status']])$(id).onchange=e=>{S[key]=e.target.value;renderDashboard(mergedData())};$('resetFilters').onclick=()=>{resetFilters();rebuild()};$('exportCsv').onclick=exportCsv;
}
loadProjects();bind();renderAll();
})();
