(()=>{'use strict';
const D=window.WORK_MONITOR_DATA;if(!D)return;
const $=id=>document.getElementById(id),S={year:'3',q:'',province:'',risk:'',urgent:false};
const RL={critical:'วิกฤต',high:'เสี่ยงสูง',watch:'เฝ้าระวัง',on_track:'ตามแผน',future:'ยังไม่ถึงแผน',completed:'ปิดงานแล้ว'},RA={critical:'เร่งทันที',high:'ต้องเร่ง',watch:'เฝ้าระวัง',on_track:'ตามต่อ',future:'ยังไม่ถึงแผน',completed:'ปิดงาน'},SL={C:'เสร็จแล้ว',O:'เลยกำหนด',D:'ล่าช้า',I:'กำลังทำ',N:'ยังไม่เริ่ม'},SC={C:'complete',O:'overdue',D:'delayed',I:'in_progress',N:'not_started'},RO={critical:0,high:1,watch:2,on_track:3,future:4,completed:5};
const money=n=>new Intl.NumberFormat('th-TH',{maximumFractionDigits:0}).format(n||0),pct=n=>`${(Math.max(0,n||0)*100).toFixed((n||0)>=1?0:1)}%`,esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])),badge=r=>`<span class="badge ${r}">${RL[r]}</span>`;
function sourceDate(){try{return new Intl.DateTimeFormat('th-TH',{day:'numeric',month:'short',year:'numeric'}).format(new Date(D.sourceModified))}catch{return D.sourceModified||'ไม่ระบุ'}}
function all(){return D.years[S.year].plots}function rows(){let q=S.q.trim().toLowerCase();return all().filter(p=>(!S.province||p.province===S.province)&&(!S.risk||p.risk===S.risk)&&(!S.urgent||['critical','high','watch'].includes(p.risk))&&(!q||[p.id,p.province].join(' ').toLowerCase().includes(q)))}
function issue(p){let o={O:0,D:1,I:2,N:3,C:4};return [...p.installments].filter(i=>i.status!=='C').sort((a,b)=>(o[a.status]??9)-(o[b.status]??9)||a.no-b.no)[0]||null}
function kpi(a,b,c,d=''){return `<article class="card kpi ${d}"><div class="label">${a}</div><div class="value">${b}</div><div class="sub">${c}</div></article>`}
function renderKpis(){let s=D.years[S.year].summary,r=rows(),urgent=r.filter(p=>['critical','high','watch'].includes(p.risk)).length,bad=r.flatMap(p=>p.installments).filter(i=>['O','D'].includes(i.status)).length;$('kpis').innerHTML=kpi('แปลงทั้งหมด',r.length,`จาก ${s.plots} แปลงในปีที่ ${S.year}`)+kpi('แผน',pct(s.plan),`Plan value ฿${money(s.planValue)}`)+kpi('Progress',pct(s.progress),`ทำได้ ฿${money(s.progressValue)}`,'good')+kpi('แปลงต้องเร่ง',urgent,`${s.riskCounts.critical||0} วิกฤต · ${s.riskCounts.high||0} เสี่ยงสูง`,'danger')+kpi('งวดติดขัด',bad,'Overdue / Delayed ในผลกรองปัจจุบัน','danger')+kpi('Gap งานตามแผน','฿'+money(s.gapValue),S.year==='2'?'ปิดงานครบตามแผน':'Plan value − Progress value','danger')}
function renderActions(){let r=rows().filter(p=>['critical','high','watch'].includes(p.risk)).sort((a,b)=>RO[a.risk]-RO[b.risk]||b.gapValue-a.gapValue||b.delayDays-a.delayDays).slice(0,14);if(!r.length){$('actionQueue').innerHTML=`<div class="empty">${S.year==='2'?'ปีที่ 2 ปิดงานครบทุกแปลงแล้ว':'ไม่พบแปลงที่ต้องเร่งในตัวกรองนี้'}</div>`;return}$('actionQueue').innerHTML=r.map(p=>{let i=issue(p),txt=i?`งวดที่${i.no} · ${SL[i.status]}`:'ยังไม่พบงวดที่ผิดปกติ';return `<div class="action-item" data-plot="${p.id}"><span class="priority ${p.risk}">${RA[p.risk]}</span><div><div class="action-id">${p.id}</div><div class="action-meta">${esc(p.province)}</div></div><div class="action-progress"><div class="mini-track"><div class="mini-fill" style="width:${Math.min(p.progress*100,100)}%"></div></div><div class="action-gap">Plan ${pct(p.plan)} · Progress ${pct(p.progress)} · <b>Gap ${p.gapPp.toFixed(1)} จุด</b>${p.delayDays?` · ช้า ${p.delayDays.toFixed(1)} วัน`:''}</div></div><div class="action-issue"><b>${txt}</b>${i?`${esc(i.start)} → ${esc(i.end)}`:''}</div><div class="action-impact"><span>Impact</span><strong>฿${money(p.gapValue)}</strong></div></div>`}).join('');bind()}
function renderInst(){let a=rows().flatMap(p=>p.installments),c={complete:0,overdue:0,delayed:0,in_progress:0,not_started:0},labels={complete:'เสร็จแล้ว',overdue:'เลยกำหนด',delayed:'ล่าช้า',in_progress:'กำลังทำ',not_started:'ยังไม่เริ่ม'};a.forEach(i=>c[SC[i.status]]++);let t=a.length||1;$('installmentHealth').innerHTML=`<div class="status-summary">${Object.keys(labels).map(k=>`<div class="status-row"><span>${labels[k]}</span><div class="status-bar"><div class="status-fill ${k}" style="width:${c[k]/t*100}%"></div></div><b>${c[k]}</b></div>`).join('')}</div><div class="status-foot"><b>${c.overdue+c.delayed} งวด</b> มีสัญญาณ Overdue/Delayed ในผลกรองปัจจุบัน${S.year==='3'?` · อีก ${c.in_progress} งวดกำลังดำเนินงาน`:''}</div>`}
function renderProvinces(){let g={};rows().forEach(p=>{let x=g[p.province]||(g[p.province]={total:0,urgent:0,gap:0});x.total++;if(['critical','high','watch'].includes(p.risk))x.urgent++;x.gap+=p.gapValue});let a=Object.entries(g).sort((a,b)=>(b[1].urgent/b[1].total)-(a[1].urgent/a[1].total)||b[1].gap-a[1].gap).slice(0,15);$('provinceHealth').innerHTML=a.map(([n,x])=>`<div class="province-item" data-province="${esc(n)}"><div class="province-top"><span>${esc(n)}</span><span>${x.urgent}/${x.total} ต้องเร่ง</span></div><div class="province-sub">Gap ฿${money(x.gap)}</div><div class="province-track"><div class="province-fill" style="width:${x.urgent/x.total*100}%"></div></div></div>`).join('')||'<div class="empty">ไม่มีข้อมูล</div>';document.querySelectorAll('[data-province]').forEach(e=>e.onclick=()=>{S.province=e.dataset.province;$('province').value=S.province;render()})}
function renderTable(){let r=rows().sort((a,b)=>RO[a.risk]-RO[b.risk]||b.gapValue-a.gapValue||a.id.localeCompare(b.id,'th',{numeric:true}));$('tableMeta').textContent=`${r.length} แปลง · ปีที่ ${S.year} · คลิกแถวเพื่อดูรายละเอียดงวด`;$('plotRows').innerHTML=r.map(p=>{let i=issue(p),ic=i?SC[i.status]:'';return `<tr data-plot="${p.id}"><td><div class="plot-id">${p.id}</div><div class="small">${esc(p.start)} → ${esc(p.end)}</div></td><td>${esc(p.province)}</td><td>${badge(p.risk)}</td><td class="pct-cell"><div class="inline-pct"><div class="mini-track"><div class="mini-fill" style="width:${Math.min(p.plan*100,100)}%;background:#9ba9a5"></div></div><span>${pct(p.plan)}</span></div></td><td class="pct-cell"><div class="inline-pct"><div class="mini-track"><div class="mini-fill" style="width:${Math.min(p.progress*100,100)}%"></div></div><span>${pct(p.progress)}</span></div></td><td class="num ${p.gapPp?'negative':''}">${p.gapPp?p.gapPp.toFixed(1)+' pp':'—'}</td><td class="num ${p.delayDays?'negative':''}">${p.delayDays?p.delayDays.toFixed(1)+' วัน':'—'}</td><td>${i?`<span class="issue-${ic}">งวดที่${i.no} · ${SL[i.status]}</span>`:'—'}</td><td class="num">${p.gapValue?'฿'+money(p.gapValue):'—'}</td></tr>`}).join('')||'<tr><td colspan="9"><div class="empty">ไม่พบรายการ</div></td></tr>';bind()}
function bind(){document.querySelectorAll('[data-plot]').forEach(e=>e.onclick=()=>openPlot(e.dataset.plot))}
function openPlot(id){let p=all().find(x=>x.id===id);if(!p)return;let body=p.installments.map(i=>`<div class="inst"><div class="name">งวดที่${i.no}</div><div class="dates">${esc(i.start)}<br>→ ${esc(i.end)}</div><div class="prog"><span>Plan ${pct(i.plan)} · Progress ${pct(i.progress)}</span><div class="mini-track"><div class="mini-fill" style="width:${Math.min(i.progress*100,100)}%"></div></div></div><div>${i.activityCount} กิจกรรม</div><div class="st"><span class="issue-${SC[i.status]}">${SL[i.status]}</span>${i.varianceDays<0?`<div class="small negative">ช้า ${Math.abs(i.varianceDays).toFixed(1)} วัน</div>`:''}</div></div>`).join('');$('modalContent').innerHTML=`<header class="modal-head"><div class="eyebrow" style="color:var(--green)">PLOT DETAIL · ปีที่ ${S.year}</div><h2>${p.id} · ${esc(p.province)}</h2><div class="small">${esc(p.start)} → ${esc(p.end)}</div></header><div class="modal-body"><div class="detail-grid"><div class="detail"><div class="label">ระดับติดตาม</div><div class="value">${badge(p.risk)}</div></div><div class="detail"><div class="label">Plan</div><div class="value">${pct(p.plan)}</div></div><div class="detail"><div class="label">Progress</div><div class="value">${pct(p.progress)}</div></div><div class="detail"><div class="label">Gap</div><div class="value ${p.gapPp?'negative':''}">${p.gapPp.toFixed(1)} pp ${p.delayDays?`· ${p.delayDays.toFixed(1)} วัน`:''}</div></div></div><section><div class="panel-head"><div><h2>งวดงาน</h2><p>${p.installments.length} งวด</p></div></div><div class="installments">${body}</div></section><div class="modal-note">ข้อมูลหน้านี้สรุปจาก tab ปีที่ ${S.year}. สถานะ O/D/I/N/C ถูกใช้เป็นสัญญาณติดตามงาน แต่ไฟล์ไม่ได้ระบุสาเหตุจริงของความล่าช้า.</div></div>`;$('modalBackdrop').hidden=false;document.body.style.overflow='hidden'}
function close(){$('modalBackdrop').hidden=true;document.body.style.overflow=''}
function csv(){let h=['Year','Plot','Province','Risk','Plan %','Progress %','Gap pp','Delay days','Current installment','Installment status','Gap value'],a=rows().map(p=>{let i=issue(p);return[S.year,p.id,p.province,RL[p.risk],p.plan,p.progress,p.gapPp,p.delayDays,i?`งวดที่${i.no}`:'',i?SL[i.status]:'',p.gapValue]}),text=[h,...a].map(r=>r.map(x=>`"${String(x??'').replace(/"/g,'""')}"`).join(',')).join('\n'),b=new Blob(['\ufeff'+text],{type:'text/csv;charset=utf-8'}),x=document.createElement('a');x.href=URL.createObjectURL(b);x.download=`work-progress-year-${S.year}.csv`;x.click();URL.revokeObjectURL(x.href)}
function provinces(){let a=[...new Set(all().map(p=>p.province))].sort((a,b)=>a.localeCompare(b,'th'));$('province').innerHTML='<option value="">ทั้งหมด</option>'+a.map(p=>`<option>${esc(p)}</option>`).join('');$('province').value=S.province}
function render(){provinces();renderKpis();renderActions();renderInst();renderProvinces();renderTable();document.querySelectorAll('.year-btn').forEach(b=>b.classList.toggle('active',b.dataset.year===S.year))}
document.querySelectorAll('.year-btn').forEach(b=>b.onclick=()=>{S.year=b.dataset.year;S.province=S.risk='';S.urgent=false;$('province').value=$('risk').value='';$('urgentOnly').checked=false;render()});$('search').oninput=e=>{S.q=e.target.value;render()};$('province').onchange=e=>{S.province=e.target.value;render()};$('risk').onchange=e=>{S.risk=e.target.value;render()};$('urgentOnly').onchange=e=>{S.urgent=e.target.checked;render()};$('reset').onclick=()=>{S.q=S.province=S.risk='';S.urgent=false;$('search').value=$('province').value=$('risk').value='';$('urgentOnly').checked=false;render()};$('exportCsv').onclick=csv;$('modalClose').onclick=close;$('modalBackdrop').onclick=e=>{if(e.target===$('modalBackdrop'))close()};document.onkeydown=e=>{if(e.key==='Escape')close()};$('snapshot').innerHTML=`ข้อมูลจาก tab ปี 2 / ปี 3<br><b>ไฟล์แก้ไขล่าสุด ${sourceDate()}</b>`;render();
})();
