(()=>{'use strict';
const D=window.WORK_MONITOR_DATA;if(!D)return;
const $=id=>document.getElementById(id);
const S={year:'3',q:'',province:'',risk:'',urgent:false,view:'overview'};
const RL={critical:'วิกฤต',high:'เสี่ยงสูง',watch:'เฝ้าระวัง',on_track:'ตามแผน',future:'ยังไม่ถึงแผน',completed:'ปิดงานแล้ว'};
const RA={critical:'เร่งทันที',high:'ต้องเร่ง',watch:'เฝ้าระวัง',on_track:'ตามต่อ',future:'ยังไม่ถึงแผน',completed:'ปิดงาน'};
const SL={C:'เสร็จแล้ว',O:'เลยกำหนด',D:'ล่าช้า',I:'กำลังทำ',N:'ยังไม่เริ่ม'};
const SC={C:'complete',O:'overdue',D:'delayed',I:'in_progress',N:'not_started'};
const RO={critical:0,high:1,watch:2,on_track:3,future:4,completed:5};
const pct=n=>`${(Math.max(0,n||0)*100).toFixed((n||0)>=1?0:1)}%`;
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const badge=r=>`<span class="badge ${r}">${RL[r]}</span>`;
function sourceDate(){try{return new Intl.DateTimeFormat('th-TH',{day:'numeric',month:'short',year:'numeric'}).format(new Date(D.sourceModified))}catch{return D.sourceModified||'ไม่ระบุ'}}
function all(){return D.years[S.year].plots}
function baseRows(){const q=S.q.trim().toLowerCase();return all().filter(p=>(!S.province||p.province===S.province)&&(!S.urgent||['critical','high','watch'].includes(p.risk))&&(!q||[p.id,p.province].join(' ').toLowerCase().includes(q)))}
function rows(){return baseRows().filter(p=>!S.risk||p.risk===S.risk)}
function issue(p){const rank={O:0,D:1,I:2,N:3,C:4};return [...p.installments].filter(i=>i.status!=='C').sort((a,b)=>(rank[a.status]??9)-(rank[b.status]??9)||a.no-b.no)[0]||null}
function plotIssueStatus(p){return issue(p)?.status||'C'}
function kpi(a,b,c,cls=''){return `<article class="card kpi ${cls}"><div class="label">${a}</div><div class="value">${b}</div><div class="sub">${c}</div></article>`}
function avg(list,key){return list.length?list.reduce((s,x)=>s+(x[key]||0),0)/list.length:0}
function renderKpis(){const r=rows(),plan=avg(r,'plan'),progress=avg(r,'progress'),gap=Math.max(plan-progress,0)*100,urgent=r.filter(p=>['critical','high','watch'].includes(p.risk)).length,blocked=r.filter(p=>['O','D'].includes(plotIssueStatus(p))).length;$('kpis').innerHTML=kpi('แปลงในผลกรอง',r.length,`จาก ${all().length} แปลงในปีที่ ${S.year}`)+kpi('Plan เฉลี่ย',pct(plan),'เฉลี่ยระดับแปลงในผลกรอง')+kpi('Progress เฉลี่ย',pct(progress),'เฉลี่ยระดับแปลงในผลกรอง','good')+kpi('Gap เฉลี่ย',gap.toFixed(1)+' จุด','Plan − Progress','danger')+kpi('แปลงต้องเร่ง',urgent,'วิกฤต / เสี่ยงสูง / เฝ้าระวัง','danger')+kpi('แปลงติดขัด',blocked,'มีสถานะล่าสุดเป็น Overdue / Delayed','danger')}
function renderActions(){const r=rows().filter(p=>['critical','high','watch'].includes(p.risk)).sort((a,b)=>RO[a.risk]-RO[b.risk]||b.gapPp-a.gapPp||b.delayDays-a.delayDays).slice(0,16);if(!r.length){$('actionQueue').innerHTML=`<div class="empty">${S.year==='2'?'ปีที่ 2 ปิดงานครบทุกแปลงแล้ว':'ไม่พบแปลงที่ต้องเร่งในตัวกรองนี้'}</div>`;return}$('actionQueue').innerHTML=r.map(p=>{const i=issue(p),txt=i?`งวดที่${i.no} · ${SL[i.status]}`:'ยังไม่พบงวดที่ผิดปกติ';return `<div class="action-item" data-plot="${p.id}"><span class="priority ${p.risk}">${RA[p.risk]}</span><div><div class="action-id">${p.id}</div><div class="action-meta">${esc(p.province)}</div></div><div class="action-progress"><div class="mini-track"><div class="mini-fill" style="width:${Math.min(p.progress*100,100)}%"></div></div><div class="action-gap">Plan ${pct(p.plan)} · Progress ${pct(p.progress)} · <b>Gap ${p.gapPp.toFixed(1)} จุด</b>${p.delayDays?` · ช้า ${p.delayDays.toFixed(1)} วัน`:''}</div></div><div class="action-issue"><b>${txt}</b>${i?`${esc(i.start)} → ${esc(i.end)}`:''}</div></div>`}).join('');bind()}
function polar(cx,cy,r,angle){const rad=(angle-90)*Math.PI/180;return{x:cx+r*Math.cos(rad),y:cy+r*Math.sin(rad)}}
function donutPath(start,end){const cx=120,cy=120,outer=104,inner=62,safe=Math.min(end,start+359.999),p1=polar(cx,cy,outer,start),p2=polar(cx,cy,outer,safe),p3=polar(cx,cy,inner,safe),p4=polar(cx,cy,inner,start),large=safe-start>180?1:0;return `M ${p1.x.toFixed(3)} ${p1.y.toFixed(3)} A ${outer} ${outer} 0 ${large} 1 ${p2.x.toFixed(3)} ${p2.y.toFixed(3)} L ${p3.x.toFixed(3)} ${p3.y.toFixed(3)} A ${inner} ${inner} 0 ${large} 0 ${p4.x.toFixed(3)} ${p4.y.toFixed(3)} Z`}
function riskKeys(){return S.year==='2'?['completed']:['critical','high','watch','on_track','future']}
function showRiskTooltip(shell,key,groups){const box=shell.querySelector('.risk-tooltip'),plots=groups[key]||[];if(!box)return;box.innerHTML=`<div class="risk-tooltip-head"><span><i class="risk-dot ${key}"></i>${RL[key]}</span><b>${plots.length} แปลง</b></div><div class="risk-tooltip-list">${plots.length?plots.map(p=>`<span>${esc(p.id)}</span>`).join(''):'<span>ไม่มีแปลงในสถานะนี้</span>'}</div><div class="risk-tooltip-action">คลิกกราฟหรือรายการสถานะ เพื่อไปที่ “ติดตามงาน” พร้อมเลือก Filter นี้</div>`;box.hidden=false}
function goToRisk(key){S.risk=key;S.view='tracking';$('risk').value=key;render();requestAnimationFrame(()=>$('trackingSection')?.scrollIntoView({behavior:'smooth',block:'start'}))}
function renderRiskChart(){const source=baseRows(),keys=riskKeys(),groups=Object.fromEntries(keys.map(k=>[k,source.filter(p=>p.risk===k).sort((a,b)=>a.id.localeCompare(b.id,'th',{numeric:true}))])),total=source.length||1;let angle=0;const slices=keys.map(k=>{const count=groups[k].length;if(!count)return'';const sweep=count/total*360,path=donutPath(angle,angle+sweep);angle+=sweep;return `<path class="risk-slice ${k}" data-risk="${k}" d="${path}" tabindex="0" role="button" aria-label="${RL[k]} ${count} แปลง"></path>`}).join('');const statusCounts={O:0,D:0,I:0,N:0,C:0};source.forEach(p=>statusCounts[plotIssueStatus(p)]++);$('installmentHealth').innerHTML=`<div class="risk-donut-shell"><div class="risk-donut-stage"><svg class="risk-donut" viewBox="0 0 240 240" role="img" aria-label="Risk Distribution"><circle class="risk-donut-track" cx="120" cy="120" r="83" fill="none" stroke-width="42"></circle>${slices}</svg><div class="risk-donut-center"><strong>${source.length}</strong><span>แปลงทั้งหมด</span></div></div><div class="risk-donut-info"><div class="risk-legend">${keys.map(k=>`<button type="button" class="risk-legend-item" data-risk="${k}"><span><i class="risk-dot ${k}"></i>${RL[k]}</span><b>${groups[k].length}</b></button>`).join('')}</div><div class="risk-tooltip" hidden></div><div class="risk-foot">สถานะติดขัดระดับแปลง: <b>${statusCounts.O} แปลง Overdue</b> · <b>${statusCounts.D} แปลง Delayed</b> · ${statusCounts.I} แปลง In progress</div></div></div>`;const shell=$('installmentHealth').querySelector('.risk-donut-shell'),sliceEls=shell.querySelectorAll('.risk-slice'),legendEls=shell.querySelectorAll('.risk-legend-item');const activate=e=>{const key=e.dataset.risk;sliceEls.forEach(x=>x.classList.toggle('is-active',x.dataset.risk===key));legendEls.forEach(x=>x.classList.toggle('is-active',x.dataset.risk===key));showRiskTooltip(shell,key,groups)},clear=()=>{sliceEls.forEach(x=>x.classList.remove('is-active'));legendEls.forEach(x=>x.classList.remove('is-active'));const box=shell.querySelector('.risk-tooltip');if(box)box.hidden=true};sliceEls.forEach(e=>{e.onpointerenter=()=>activate(e);e.onfocus=()=>activate(e);e.onclick=()=>goToRisk(e.dataset.risk);e.onkeydown=x=>{if(x.key==='Enter'||x.key===' '){x.preventDefault();goToRisk(e.dataset.risk)}}});legendEls.forEach(e=>{e.onpointerenter=()=>activate(e);e.onfocus=()=>activate(e);e.onclick=()=>goToRisk(e.dataset.risk)});shell.onmouseleave=clear}
function renderProvinces(){const g={};rows().forEach(p=>{const x=g[p.province]||(g[p.province]={total:0,urgent:0});x.total++;if(['critical','high','watch'].includes(p.risk))x.urgent++});const a=Object.entries(g).sort((a,b)=>(b[1].urgent/b[1].total)-(a[1].urgent/a[1].total)||b[1].urgent-a[1].urgent||b[1].total-a[1].total).slice(0,15);$('provinceHealth').innerHTML=a.map(([n,x])=>{const ratio=x.total?x.urgent/x.total:0;return `<div class="province-item" data-province="${esc(n)}"><div class="province-top"><span>${esc(n)}</span><span>${x.urgent}/${x.total} ต้องเร่ง</span></div><div class="province-sub">${(ratio*100).toFixed(0)}% ของแปลงในจังหวัดนี้อยู่ในกลุ่มต้องเร่ง</div><div class="province-track"><div class="province-fill" style="width:${ratio*100}%"></div></div></div>`}).join('')||'<div class="empty">ไม่มีข้อมูล</div>';document.querySelectorAll('[data-province]').forEach(e=>e.onclick=()=>{S.province=e.dataset.province;$('province').value=S.province;render()})}
function renderTable(){const r=rows().sort((a,b)=>RO[a.risk]-RO[b.risk]||b.gapPp-a.gapPp||b.delayDays-a.delayDays||a.id.localeCompare(b.id,'th',{numeric:true}));$('tableMeta').textContent=`${r.length} แปลง · ปีที่ ${S.year} · คลิกแถวเพื่อดูรายละเอียดงวด`;$('plotRows').innerHTML=r.map(p=>{const i=issue(p),ic=i?SC[i.status]:'';return `<tr data-plot="${p.id}"><td><div class="plot-id">${p.id}</div><div class="small">${esc(p.start)} → ${esc(p.end)}</div></td><td>${esc(p.province)}</td><td>${badge(p.risk)}</td><td class="pct-cell"><div class="inline-pct"><div class="mini-track"><div class="mini-fill" style="width:${Math.min(p.plan*100,100)}%;background:#9ba9a5"></div></div><span>${pct(p.plan)}</span></div></td><td class="pct-cell"><div class="inline-pct"><div class="mini-track"><div class="mini-fill" style="width:${Math.min(p.progress*100,100)}%"></div></div><span>${pct(p.progress)}</span></div></td><td class="num ${p.gapPp?'negative':''}">${p.gapPp?p.gapPp.toFixed(1)+' pp':'—'}</td><td class="num ${p.delayDays?'negative':''}">${p.delayDays?p.delayDays.toFixed(1)+' วัน':'—'}</td><td>${i?`<span class="issue-${ic}">งวดที่${i.no} · ${SL[i.status]}</span>`:'—'}</td></tr>`}).join('')||'<tr><td colspan="8"><div class="empty">ไม่พบรายการ</div></td></tr>';bind()}
function bind(){document.querySelectorAll('[data-plot]').forEach(e=>e.onclick=()=>openPlot(e.dataset.plot))}
function openPlot(id){const p=all().find(x=>x.id===id);if(!p)return;const body=p.installments.map(i=>`<div class="inst"><div class="name">งวดที่${i.no}</div><div class="dates">${esc(i.start)}<br>→ ${esc(i.end)}</div><div class="prog"><span>Plan ${pct(i.plan)} · Progress ${pct(i.progress)}</span><div class="mini-track"><div class="mini-fill" style="width:${Math.min(i.progress*100,100)}%"></div></div></div><div>${i.activityCount} กิจกรรม</div><div class="st"><span class="issue-${SC[i.status]}">${SL[i.status]}</span>${i.varianceDays<0?`<div class="small negative">ช้า ${Math.abs(i.varianceDays).toFixed(1)} วัน</div>`:''}</div></div>`).join('');$('modalContent').innerHTML=`<header class="modal-head"><div class="eyebrow" style="color:var(--green)">PLOT DETAIL · ปีที่ ${S.year}</div><h2>${p.id} · ${esc(p.province)}</h2><div class="small">${esc(p.start)} → ${esc(p.end)}</div></header><div class="modal-body"><div class="detail-grid"><div class="detail"><div class="label">ระดับติดตาม</div><div class="value">${badge(p.risk)}</div></div><div class="detail"><div class="label">Plan</div><div class="value">${pct(p.plan)}</div></div><div class="detail"><div class="label">Progress</div><div class="value">${pct(p.progress)}</div></div><div class="detail"><div class="label">Gap</div><div class="value ${p.gapPp?'negative':''}">${p.gapPp.toFixed(1)} pp ${p.delayDays?`· ${p.delayDays.toFixed(1)} วัน`:''}</div></div></div><section><div class="panel-head"><div><h2>รายละเอียดงวดงาน</h2><p>${p.installments.length} งวดในแปลงนี้</p></div></div><div class="installments">${body}</div></section><div class="modal-note">Dashboard ใช้ “แปลง” เป็นหน่วยนับหลัก ส่วนข้อมูลรายงวดใช้เพื่อระบุว่างานของแปลงนั้นติดอยู่ที่งวดใด.</div></div>`;$('modalBackdrop').hidden=false;document.body.style.overflow='hidden'}
function close(){$('modalBackdrop').hidden=true;document.body.style.overflow=''}
function csv(){const h=['Year','Plot','Province','Risk','Plan %','Progress %','Gap pp','Delay days','Current installment','Installment status'],a=rows().map(p=>{const i=issue(p);return[S.year,p.id,p.province,RL[p.risk],p.plan,p.progress,p.gapPp,p.delayDays,i?`งวดที่${i.no}`:'',i?SL[i.status]:'']}),text=[h,...a].map(r=>r.map(x=>`"${String(x??'').replace(/"/g,'""')}"`).join(',')).join('\n'),b=new Blob(['\ufeff'+text],{type:'text/csv;charset=utf-8'}),x=document.createElement('a');x.href=URL.createObjectURL(b);x.download=`work-progress-year-${S.year}.csv`;x.click();URL.revokeObjectURL(x.href)}
function provinces(){const a=[...new Set(all().map(p=>p.province))].sort((a,b)=>a.localeCompare(b,'th'));$('province').innerHTML='<option value="">ทั้งหมด</option>'+a.map(p=>`<option>${esc(p)}</option>`).join('');$('province').value=S.province}
function renderView(){document.querySelectorAll('.view-content').forEach(x=>x.classList.toggle('active',x.id===(S.view==='overview'?'overviewContent':'trackingContent')));document.querySelectorAll('.view-btn').forEach(x=>x.classList.toggle('active',x.dataset.view===S.view))}
function render(){provinces();renderKpis();renderRiskChart();renderActions();renderProvinces();renderTable();renderView();document.querySelectorAll('.year-btn').forEach(b=>b.classList.toggle('active',b.dataset.year===S.year))}
document.querySelectorAll('.year-btn').forEach(b=>b.onclick=()=>{S.year=b.dataset.year;S.province=S.risk='';S.urgent=false;S.view='overview';$('province').value=$('risk').value='';$('urgentOnly').checked=false;render()});
document.querySelectorAll('.view-btn').forEach(b=>b.onclick=()=>{S.view=b.dataset.view;renderView()});
$('search').oninput=e=>{S.q=e.target.value;render()};$('province').onchange=e=>{S.province=e.target.value;render()};$('risk').onchange=e=>{S.risk=e.target.value;render()};$('urgentOnly').onchange=e=>{S.urgent=e.target.checked;render()};$('reset').onclick=()=>{S.q=S.province=S.risk='';S.urgent=false;$('search').value=$('province').value=$('risk').value='';$('urgentOnly').checked=false;render()};$('exportCsv').onclick=csv;$('modalClose').onclick=close;$('modalBackdrop').onclick=e=>{if(e.target===$('modalBackdrop'))close()};document.onkeydown=e=>{if(e.key==='Escape')close()};$('snapshot').innerHTML=`ข้อมูลจาก tab ปี 2 / ปี 3<br><b>ไฟล์แก้ไขล่าสุด ${sourceDate()}</b>`;render();
})();
