(()=>{'use strict';
const $=id=>document.getElementById(id);
const RL={critical:'วิกฤต',high:'เสี่ยงสูง',watch:'เฝ้าระวัง',on_track:'ตามแผน',future:'ยังไม่ถึงแผน',completed:'ปิดงานแล้ว'};
const RA={critical:'เร่งทันที',high:'ต้องเร่ง',watch:'เฝ้าระวัง',on_track:'ตามต่อ',future:'ยังไม่ถึงแผน',completed:'ปิดงาน'};
const SL={C:'เสร็จแล้ว',O:'เลยกำหนด',D:'ล่าช้า',I:'กำลังทำ',N:'ยังไม่เริ่ม'};
const SC={C:'complete',O:'overdue',D:'delayed',I:'in_progress',N:'not_started'};
const RO={critical:0,high:1,watch:2,on_track:3,future:4,completed:5};
const S={files:[],data:null,year:null,q:'',province:'',risk:'',urgent:false,view:'overview',mergeWarnings:[]};
const pct=n=>`${(Math.max(0,n||0)*100).toFixed((n||0)>=1?0:1)}%`;
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const badge=r=>`<span class="badge ${r}">${RL[r]}</span>`;
function current(){return S.data?.years?.[S.year]}
function all(){return current()?.plots||[]}
function baseRows(){const q=S.q.trim().toLowerCase();return all().filter(p=>(!S.province||p.province===S.province)&&(!S.urgent||['critical','high','watch'].includes(p.risk))&&(!q||[p.id,p.province,p.description,p.sourceFile].join(' ').toLowerCase().includes(q)))}
function rows(){return baseRows().filter(p=>!S.risk||p.risk===S.risk)}
function issue(p){const rank={O:0,D:1,I:2,N:3,C:4};return [...p.installments].filter(i=>i.status!=='C').sort((a,b)=>(rank[a.status]??9)-(rank[b.status]??9)||a.no-b.no)[0]||null}
function kpi(a,b,c,cls=''){return `<article class="card kpi ${cls}"><div class="label">${a}</div><div class="value">${b}</div><div class="sub">${c}</div></article>`}
function weighted(list,key){const w=list.reduce((s,p)=>s+(p.contractValue||0),0);if(w>0)return list.reduce((s,p)=>s+(p.contractValue||0)*(p[key]||0),0)/w;return list.length?list.reduce((s,p)=>s+(p[key]||0),0)/list.length:0}
function renderKpis(){const r=rows(),plan=weighted(r,'plan'),progress=weighted(r,'progress'),gap=Math.max(plan-progress,0)*100,urgent=r.filter(p=>['critical','high','watch'].includes(p.risk)).length,problems=r.filter(p=>{const i=issue(p);return i&&['O','D'].includes(i.status)}).length;$('kpis').innerHTML=kpi('แปลงในผลกรอง',r.length,`จาก ${all().length} แปลงในปีที่ ${current().yearLabel}`)+kpi('Plan',pct(plan),'คำนวณจากแปลงในผลกรอง')+kpi('Progress',pct(progress),'คำนวณจากแปลงในผลกรอง','good')+kpi('Gap',gap.toFixed(1)+' จุด','Plan − Progress','danger')+kpi('แปลงต้องเร่ง',urgent,'วิกฤต / เสี่ยงสูง / เฝ้าระวัง','danger')+kpi('แปลงติดขัด',problems,'มีงวด Overdue / Delayed','danger')}
function renderActions(){const r=rows().filter(p=>['critical','high','watch'].includes(p.risk)).sort((a,b)=>RO[a.risk]-RO[b.risk]||b.gapPp-a.gapPp||b.delayDays-a.delayDays).slice(0,18);$('actionQueue').innerHTML=r.length?r.map(p=>{const i=issue(p),txt=i?`งวดที่ ${i.no} · ${SL[i.status]}`:'ยังไม่พบงวดที่ผิดปกติ';return `<div class="action-item" data-plot="${p.id}"><span class="priority ${p.risk}">${RA[p.risk]}</span><div><div class="action-id">${p.id}</div><div class="action-meta">${esc(p.province)}</div></div><div class="action-progress"><div class="mini-track"><div class="mini-fill" style="width:${Math.min(p.progress*100,100)}%"></div></div><div class="action-gap">Plan ${pct(p.plan)} · Progress ${pct(p.progress)} · <b>Gap ${p.gapPp.toFixed(1)} จุด</b>${p.delayDays?` · ช้า ${p.delayDays.toFixed(1)} วัน`:''}</div></div><div class="action-issue"><b>${txt}</b>${i?`${esc(i.start)} → ${esc(i.end)}`:''}</div></div>`}).join(''):`<div class="empty">ไม่พบแปลงที่ต้องเร่งในตัวกรองนี้</div>`;bindPlots()}
function polar(cx,cy,r,a){const rad=(a-90)*Math.PI/180;return{x:cx+r*Math.cos(rad),y:cy+r*Math.sin(rad)}}
function donutPath(start,end){const cx=120,cy=120,outer=104,inner=62,safe=Math.min(end,start+359.999),p1=polar(cx,cy,outer,start),p2=polar(cx,cy,outer,safe),p3=polar(cx,cy,inner,safe),p4=polar(cx,cy,inner,start),large=safe-start>180?1:0;return `M ${p1.x.toFixed(3)} ${p1.y.toFixed(3)} A ${outer} ${outer} 0 ${large} 1 ${p2.x.toFixed(3)} ${p2.y.toFixed(3)} L ${p3.x.toFixed(3)} ${p3.y.toFixed(3)} A ${inner} ${inner} 0 ${large} 0 ${p4.x.toFixed(3)} ${p4.y.toFixed(3)} Z`}
function riskKeys(){const present=new Set(baseRows().map(p=>p.risk)),preferred=['critical','high','watch','on_track','future','completed'];return preferred.filter(k=>present.has(k))}
function goToRisk(key){S.risk=key;S.view='tracking';$('risk').value=key;render();requestAnimationFrame(()=>$('trackingSection')?.scrollIntoView({behavior:'smooth',block:'start'}))}
function renderRisk(){const source=baseRows(),keys=riskKeys(),groups=Object.fromEntries(keys.map(k=>[k,source.filter(p=>p.risk===k).sort((a,b)=>a.id.localeCompare(b.id,'th',{numeric:true}))])),total=source.length||1;let angle=0;const slices=keys.map(k=>{const count=groups[k].length,sweep=count/total*360,path=donutPath(angle,angle+sweep);angle+=sweep;return `<path class="risk-slice ${k}" data-risk="${k}" d="${path}" tabindex="0" role="button" aria-label="${RL[k]} ${count} แปลง"></path>`}).join('');const issueCounts={O:0,D:0,I:0};source.forEach(p=>{const i=issue(p);if(i&&issueCounts[i.status]!=null)issueCounts[i.status]++});$('riskChart').innerHTML=`<div class="risk-donut-shell"><div class="risk-donut-stage"><svg class="risk-donut" viewBox="0 0 240 240"><circle class="risk-donut-track" cx="120" cy="120" r="83" fill="none" stroke-width="42"></circle>${slices}</svg><div class="risk-donut-center"><strong>${source.length}</strong><span>แปลงทั้งหมด</span></div></div><div class="risk-donut-info"><div class="risk-legend">${keys.map(k=>`<button class="risk-legend-item" data-risk="${k}"><span><i class="risk-dot ${k}"></i>${RL[k]}</span><b>${groups[k].length}</b></button>`).join('')}</div><div class="risk-tooltip" hidden></div><div class="risk-foot">จุดติดขัดระดับแปลง: <b>${issueCounts.O} Overdue</b> · <b>${issueCounts.D} Delayed</b> · ${issueCounts.I} In progress</div></div></div>`;const shell=$('riskChart').querySelector('.risk-donut-shell'),sliceEls=shell.querySelectorAll('.risk-slice'),legendEls=shell.querySelectorAll('.risk-legend-item'),tooltip=shell.querySelector('.risk-tooltip');const activate=e=>{const k=e.dataset.risk,plots=groups[k]||[];sliceEls.forEach(x=>x.classList.toggle('is-active',x.dataset.risk===k));legendEls.forEach(x=>x.classList.toggle('is-active',x.dataset.risk===k));tooltip.innerHTML=`<div class="risk-tooltip-head"><span><i class="risk-dot ${k}"></i>${RL[k]}</span><b>${plots.length} แปลง</b></div><div class="risk-tooltip-list">${plots.map(p=>`<span>${esc(p.id)}</span>`).join('')||'<span>ไม่มีแปลง</span>'}</div><div class="risk-tooltip-action">คลิกเพื่อเปิด “ติดตามงาน” พร้อม Filter สถานะนี้</div>`;tooltip.hidden=false},clear=()=>{sliceEls.forEach(x=>x.classList.remove('is-active'));legendEls.forEach(x=>x.classList.remove('is-active'));tooltip.hidden=true};sliceEls.forEach(e=>{e.onpointerenter=()=>activate(e);e.onfocus=()=>activate(e);e.onclick=()=>goToRisk(e.dataset.risk);e.onkeydown=x=>{if(x.key==='Enter'||x.key===' '){x.preventDefault();goToRisk(e.dataset.risk)}}});legendEls.forEach(e=>{e.onpointerenter=()=>activate(e);e.onfocus=()=>activate(e);e.onclick=()=>goToRisk(e.dataset.risk)});shell.onmouseleave=clear}
function renderProvinces(){const g={};rows().forEach(p=>{const x=g[p.province]||(g[p.province]={total:0,urgent:0});x.total++;if(['critical','high','watch'].includes(p.risk))x.urgent++});const a=Object.entries(g).sort((a,b)=>(b[1].urgent/b[1].total)-(a[1].urgent/a[1].total)||b[1].urgent-a[1].urgent).slice(0,18);$('provinceHealth').innerHTML=a.map(([n,x])=>{const ratio=x.total?x.urgent/x.total:0;return `<div class="province-item" data-province="${esc(n)}"><div class="province-top"><span>${esc(n)}</span><span>${x.urgent}/${x.total} ต้องเร่ง</span></div><div class="province-sub">${(ratio*100).toFixed(0)}% ของแปลงในจังหวัดนี้อยู่ในกลุ่มต้องเร่ง</div><div class="province-track"><div class="province-fill" style="width:${ratio*100}%"></div></div></div>`}).join('')||'<div class="empty">ไม่มีข้อมูล</div>';document.querySelectorAll('[data-province]').forEach(e=>e.onclick=()=>{S.province=e.dataset.province;$('province').value=S.province;render()})}
function renderTable(){const r=rows().sort((a,b)=>RO[a.risk]-RO[b.risk]||b.gapPp-a.gapPp||b.delayDays-a.delayDays||a.id.localeCompare(b.id,'th',{numeric:true}));$('tableMeta').textContent=`${r.length} แปลง · ปีที่ ${current().yearLabel} · คลิกแถวเพื่อดูรายละเอียดงวด`;$('plotRows').innerHTML=r.map(p=>{const i=issue(p),ic=i?SC[i.status]:'';return `<tr data-plot="${p.id}"><td><div class="plot-id">${p.id}</div><div class="small">${esc(p.start)} → ${esc(p.end)}</div></td><td>${esc(p.province)}</td><td>${badge(p.risk)}</td><td>${pct(p.plan)}</td><td>${pct(p.progress)}</td><td class="num ${p.gapPp?'negative':''}">${p.gapPp?p.gapPp.toFixed(1)+' pp':'—'}</td><td class="num ${p.delayDays?'negative':''}">${p.delayDays?p.delayDays.toFixed(1)+' วัน':'—'}</td><td>${i?`<span class="issue-${ic}">งวดที่ ${i.no} · ${SL[i.status]}</span>`:'—'}</td><td><span class="source-chip">${esc(p.sourceFile)}</span></td></tr>`}).join('')||'<tr><td colspan="9"><div class="empty">ไม่พบรายการ</div></td></tr>';bindPlots()}
function bindPlots(){document.querySelectorAll('[data-plot]').forEach(e=>e.onclick=()=>openPlot(e.dataset.plot))}
function openPlot(id){const p=all().find(x=>x.id===id);if(!p)return;const body=p.installments.map(i=>`<div class="inst"><div class="name">งวดที่ ${i.no}</div><div class="dates">${esc(i.start)}<br>→ ${esc(i.end)}</div><div class="prog"><span>Plan ${pct(i.plan)} · Progress ${pct(i.progress)}</span><div class="mini-track"><div class="mini-fill" style="width:${Math.min(i.progress*100,100)}%"></div></div></div><div>${i.activityCount} กิจกรรม</div><div class="st"><span class="issue-${SC[i.status]||'not_started'}">${SL[i.status]||i.status||'—'}</span>${i.varianceDays<0?`<div class="small negative">ช้า ${Math.abs(i.varianceDays).toFixed(1)} วัน</div>`:''}</div></div>`).join('')||'<div class="empty">ไม่พบแถวงวดที่อ่านได้</div>';$('modalContent').innerHTML=`<header class="modal-head"><div class="eyebrow">PLOT DETAIL · ปีที่ ${current().yearLabel}</div><h2>${p.id} · ${esc(p.province)}</h2><div class="small">แหล่งข้อมูล: ${esc(p.sourceFile)}</div></header><div class="modal-body"><div class="detail-grid"><div class="detail"><div class="label">ระดับติดตาม</div><div class="value">${badge(p.risk)}</div></div><div class="detail"><div class="label">Plan</div><div class="value">${pct(p.plan)}</div></div><div class="detail"><div class="label">Progress</div><div class="value">${pct(p.progress)}</div></div><div class="detail"><div class="label">Gap</div><div class="value ${p.gapPp?'negative':''}">${p.gapPp.toFixed(1)} pp ${p.delayDays?`· ${p.delayDays.toFixed(1)} วัน`:''}</div></div></div><section><div class="panel-head"><div><h2>งวดงาน</h2><p>${p.installments.length} งวด</p></div></div><div class="installments">${body}</div></section></div>`;$('modalBackdrop').hidden=false;document.body.style.overflow='hidden'}
function resetFilters(){S.q=S.province=S.risk='';S.urgent=false;$('search').value=$('province').value=$('risk').value='';$('urgentOnly').checked=false}
function rebuildCombined(){const years={},warnings=[];for(const rec of S.files){for(const y of Object.values(rec.parsed.years)){const key=String(y.yearLabel),bucket=years[key]||(years[key]={yearLabel:String(y.yearLabel),sheetNames:[],plots:[],warnings:[]}),byId=new Map(bucket.plots.map((p,i)=>[p.id,i]));bucket.sheetNames.push(`${rec.name} › ${y.sheetName}`);for(const p of y.plots){const tagged={...p,sourceFile:rec.name,sourceFileId:rec.id,sourceSheet:y.sheetName};if(byId.has(tagged.id)){const idx=byId.get(tagged.id),old=bucket.plots[idx];warnings.push(`ปี ${key}: Plot ${tagged.id} ซ้ำ — ใช้ ${rec.name} แทน ${old.sourceFile}`);bucket.plots[idx]=tagged}else{byId.set(tagged.id,bucket.plots.length);bucket.plots.push(tagged)}}bucket.warnings.push(...(y.warnings||[]).map(w=>`${rec.name}: ${w}`))}}S.mergeWarnings=warnings;S.data={years};const keys=Object.keys(years).sort((a,b)=>Number(b)-Number(a));if(!keys.length){S.year=null;S.data=null;$('workspace').hidden=true;$('emptyUpload').hidden=false;$('snapshot').textContent='ยังไม่มีไฟล์';return}if(!S.year||!years[S.year])S.year=keys[0];resetFilters();$('workspace').hidden=false;$('emptyUpload').hidden=true;render()}
function renderFiles(){const years=new Set;let plots=0;S.files.forEach(f=>{Object.values(f.parsed.years).forEach(y=>{years.add(String(y.yearLabel));plots+=y.plots.length})});$('fileSummary').textContent=`${S.files.length} ไฟล์ · ${years.size} ปีงาน · ${plots} แปลงก่อนรวมรายการซ้ำ`;$('snapshot').innerHTML=`${S.files.length} ไฟล์ · ปีงาน ${[...years].sort((a,b)=>Number(a)-Number(b)).map(y=>`ปี ${esc(y)}`).join(', ')}`;$('fileList').innerHTML=S.files.map(f=>{const ys=Object.values(f.parsed.years),cnt=ys.reduce((s,y)=>s+y.plots.length,0);return `<article class="file-card" data-file-id="${f.id}"><div class="file-icon">XLS</div><div class="file-card-main"><strong title="${esc(f.name)}">${esc(f.name)}</strong><div class="file-tags">${ys.map(y=>`<span>ปี ${esc(y.yearLabel)}</span>`).join('')}</div><small>${cnt} แปลงที่อ่านได้ · ${f.parsed.recognized.length} sheet ที่ใช้</small></div><button class="file-remove" data-remove-file="${f.id}" title="ลบไฟล์นี้" aria-label="ลบ ${esc(f.name)}">×</button></article>`}).join('');document.querySelectorAll('[data-remove-file]').forEach(b=>b.onclick=()=>removeFile(b.dataset.removeFile))}
function renderYears(){$('yearNav').innerHTML=Object.entries(S.data.years).sort((a,b)=>Number(b[0])-Number(a[0])).map(([k,v])=>`<button class="year-btn ${k===S.year?'active':''}" data-year="${k}"><span>ปีที่ ${esc(v.yearLabel)}</span><small>${v.plots.length} แปลง · ${v.sheetNames.length} source</small></button>`).join('');document.querySelectorAll('.year-btn').forEach(b=>b.onclick=()=>{S.year=b.dataset.year;resetFilters();S.view='overview';render()})}
function renderProvincesSelect(){const arr=[...new Set(all().map(p=>p.province))].sort((a,b)=>a.localeCompare(b,'th'));$('province').innerHTML='<option value="">ทั้งหมด</option>'+arr.map(x=>`<option>${esc(x)}</option>`).join('');$('province').value=S.province}
function renderView(){document.querySelectorAll('.view-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===S.view));$('overviewContent').classList.toggle('active',S.view==='overview');$('trackingContent').classList.toggle('active',S.view==='tracking')}
function render(){renderFiles();renderYears();renderProvincesSelect();renderKpis();renderRisk();renderActions();renderProvinces();renderTable();renderView()}
function showQuality(){const fileBlocks=S.files.map(f=>`<section class="quality-file"><h3>${esc(f.name)}</h3><div class="quality-recognized">${f.parsed.recognized.map(r=>`<div><b>${esc(r.sheetName)}</b> → ปี ${esc(r.year)} · ${r.plots} แปลง · ${r.installments} งวด${r.warnings?.length?`<br><span>${r.warnings.map(esc).join(' · ')}</span>`:''}</div>`).join('')}</div>${f.parsed.skipped.length?`<details><summary>Sheet ที่ข้าม ${f.parsed.skipped.length}</summary>${f.parsed.skipped.map(x=>`<div class="quality-skip"><b>${esc(x.sheetName)}</b> — ${esc(x.error)}</div>`).join('')}</details>`:''}</section>`).join('');$('qualityContent').innerHTML=`<header class="modal-head"><div class="eyebrow">DATA QUALITY</div><h2>การรวมข้อมูลหลายไฟล์</h2><div class="small">${S.files.length} ไฟล์ · ${Object.keys(S.data?.years||{}).length} ปีงาน</div></header><div class="modal-body"><section><h3>Merge warnings</h3>${S.mergeWarnings.length?`<ul class="warning-list">${S.mergeWarnings.map(w=>`<li>${esc(w)}</li>`).join('')}</ul>`:'<div class="quality-ok">ไม่พบ Plot ID ซ้ำข้ามไฟล์</div>'}</section>${fileBlocks}</div>`;$('qualityBackdrop').hidden=false;document.body.style.overflow='hidden'}
function csv(){const h=['Year','Plot','Province','Risk','Plan %','Progress %','Gap pp','Delay days','Current installment','Installment status','Source file'],a=rows().map(p=>{const i=issue(p);return[current().yearLabel,p.id,p.province,RL[p.risk],p.plan,p.progress,p.gapPp,p.delayDays,i?`งวดที่ ${i.no}`:'',i?SL[i.status]:'',p.sourceFile]}),t=[h,...a].map(r=>r.map(x=>`"${String(x??'').replace(/"/g,'""')}"`).join(',')).join('\n'),b=new Blob(['\ufeff'+t],{type:'text/csv;charset=utf-8'}),x=document.createElement('a');x.href=URL.createObjectURL(b);x.download=`work-progress-year-${current().yearLabel}.csv`;x.click();URL.revokeObjectURL(x.href)}
function close(id){$(id).hidden=true;if($('modalBackdrop').hidden&&$('qualityBackdrop').hidden)document.body.style.overflow=''}
function showError(msg){$('errorCard').hidden=false;$('errorCard').innerHTML=`<h3>มีไฟล์ที่อ่านไม่สำเร็จ</h3><p>${esc(msg).replace(/\n/g,'<br>')}</p><small>ไฟล์อื่นที่อ่านได้จะยังคงอยู่ใน dashboard</small>`}
async function addFiles(fileList){const files=[...(fileList||[])];if(!files.length)return;if(!window.XLSX){showError('โหลดตัวอ่าน Excel ไม่สำเร็จ กรุณาตรวจ internet แล้ว refresh หน้าเว็บ');return}$('errorCard').hidden=true;const errors=[];for(const file of files){const signature=`${file.name}|${file.size}|${file.lastModified}`;if(S.files.some(x=>x.signature===signature))continue;try{const buf=await file.arrayBuffer(),wb=XLSX.read(buf,{type:'array',cellDates:true}),parsed=window.ExcelMonitorParser.parseWorkbook(wb,file.name);S.files.push({id:`f${Date.now()}_${Math.random().toString(36).slice(2,8)}`,signature,name:file.name,size:file.size,lastModified:file.lastModified,parsed})}catch(err){console.error(err);errors.push(`${file.name}: ${err.message||'อ่านไฟล์ไม่สำเร็จ'}`)}}$('fileInput').value='';rebuildCombined();if(errors.length)showError(errors.join('\n'))}
function removeFile(id){const rec=S.files.find(x=>x.id===id);if(!rec)return;S.files=S.files.filter(x=>x.id!==id);rebuildCombined();if(S.files.length)renderFiles()}
const dz=$('dropzone');['dragenter','dragover'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.add('drag')}));['dragleave','drop'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.remove('drag')}));dz.addEventListener('drop',e=>addFiles(e.dataTransfer.files));$('fileInput').onchange=e=>addFiles(e.target.files);$('addFilesBtn').onclick=()=>{$('fileInput').value='';$('fileInput').click()};$('qualityBtn').onclick=showQuality;$('search').oninput=e=>{S.q=e.target.value;render()};$('province').onchange=e=>{S.province=e.target.value;render()};$('risk').onchange=e=>{S.risk=e.target.value;render()};$('urgentOnly').onchange=e=>{S.urgent=e.target.checked;render()};$('reset').onclick=()=>{resetFilters();render()};document.querySelectorAll('.view-btn').forEach(b=>b.onclick=()=>{S.view=b.dataset.view;renderView()});$('exportCsv').onclick=csv;$('modalClose').onclick=()=>close('modalBackdrop');$('qualityClose').onclick=()=>close('qualityBackdrop');$('modalBackdrop').onclick=e=>{if(e.target===$('modalBackdrop'))close('modalBackdrop')};$('qualityBackdrop').onclick=e=>{if(e.target===$('qualityBackdrop'))close('qualityBackdrop')};document.onkeydown=e=>{if(e.key==='Escape'){close('modalBackdrop');close('qualityBackdrop')}};
})();
